### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by craftycram** [EmotionalLove/BetterCommandSystem#1]
Hey,
I just started creating a new ReMc plugin using your BetterCommandSystem.
Because I don't really know how creating plugins works I looked at your [ChatBridge Plugin](https://github.com/EmotionalLove/ReChatBridge).
Now I'm getting crashes on ReMc once I try to load my plugin, which comes from BetterCommandSystem. I also tried it with the chatbridge plugin (downloaded and built the repo), also doesn't work.

```[Plugin Loader / INFO] Finding plugins...
[Plugin Loader / INFO] 3 potential plugins were found!
[Plugin Loader / INFO] Prepared ReMcAfkFishFarm 1.0
[Plugin Loader / INFO] Prepared ChatLoggerPlugin 1.0
[Plugin Loader / INFO] Prepared AntiAFK 1.1
Exception in thread "main" java.lang.NoClassDefFoundError: me/someonelove/bettercommandsystem/ICommand
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.sasha.reminecraft.api.RePluginLoader.lambda$loadPlugins$1(RePluginLoader.java:103)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.sasha.reminecraft.api.RePluginLoader.loadPlugins(RePluginLoader.java:100)
        at com.sasha.reminecraft.ReMinecraft.main(ReMinecraft.java:132)
Caused by: java.lang.ClassNotFoundException: me.someonelove.bettercommandsystem.ICommand
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 6 more
Exception in thread "Thread-0" java.lang.NullPointerException
        at com.sasha.reminecraft.ReMinecraft.lambda$static$0(ReMinecraft.java:93)
        at java.lang.Thread.run(Thread.java:748)
```

How can i fix this exception? Thanks in advance :/

**Comment by craftycram** [comment]
My repo if you want to try running it yourself: https://github.com/craftycram/ReMcAfkFishFarmPlugin
I am using ReMinecraft 2.0.5
